# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - release

jobs:
  allow_failures:
    - name: "18.04"
    - name: "Mac"
  include:
    - name: "18.04"
      os: linux
      dist: bionic
      env: ORdownload=or-tools_ubuntu-16.04_v7.4.7247.tar.gz ORtoolsInstallLoc=/tmp/ # Not a mistake. The ORtools compiled bundle has GLIBC issues
    - name: "16.04"
      os: linux
      dist: xenial
      env: ORdownload=or-tools_ubuntu-16.04_v7.4.7247.tar.gz ORtoolsInstallLoc=/tmp/
    - name: "Mac"
      os: osx
      env: ORdownload=or-tools_MacOsX-10.14.6_v7.4.7247.tar.gz ORtoolsInstallLoc=/tmp/
    
cache: packages

r_packages:
  - covr  #code coverage tool  
  
before_script:
  - wget -O /tmp/ORtools.tar.gz "https://github.com/google/or-tools/releases/download/v7.4/$ORdownload"
  - tar -xvf /tmp/ORtools.tar.gz -C $ORtoolsInstallLoc/
  - ln -s  $ORtoolsInstallLoc/or-tools_* $ORtoolsInstallLoc/ORtools

after_failure:
  - cat src/Makevars

after_success:
  - test $TRAVIS_OS_NAME == "linux" && travis_wait Rscript -e 'covr::codecov()' # Only produce coverage on linux builds