# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx

cache: packages

language: R
r:
  - release

r_packages:
  - covr  #code coverage tool  
  
before_script:
  - wget -O /tmp/ORtools.tar.gz https://github.com/google/or-tools/releases/download/v7.4/or-tools_ubuntu-18.04_v7.4.7247.tar.gz
  - tar -xvf /tmp/ORtools.tar.gz -C /tmp/
  - export ORtoolsDIR=/tmp/or-tools_Ubuntu-18.04-64bit_v7.4.7247/
  
after_success:
  - test $TRAVIS_OS_NAME == "linux" && travis_wait Rscript -e 'covr::codecov()' # Only produce coverage on linux builds