# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A simple knapsack solver
#' 
#' Solve knapsack proble via google's brilliant OR tools lbirary.
#' 
#' @param profits A vector of integer item profits (must be equal in length to ncol(weights))
#' @param weights A matrix (which can have a single row if one is only interested in the standard knapsack problem) of item weights
#' @param capacities A vector of length nrow(weights) of knapsack capacities
#' 
#' @return solution A named list of:
#'            'packed_items' - the 1-based indicies of items selected for packing
#'            'total_profit' - the optimised sum of profits
#'            'is_optimal' - a status flag provided by the solver
#' @references \url{https://developers.google.com/optimization/reference/algorithms/knapsack_solver/}
#' @references \url{https://en.wikipedia.org/wiki/Knapsack_problem}
#' 
#' @examples
#' # Taken from the OR-tools documentation examples:
#' 
#' SKPProfits <- c(360, 83, 59,  130, 431, 67, 230, 52,  93,  125, 670, 892, 600,
#'                     38,  48, 147, 78,  256, 63, 17,  120, 164, 432, 35,  92,  110,
#'                     22,  42, 50,  323, 514, 28, 87,  73,  78,  15,  26,  78,  210,
#'                     36,  85, 189, 274, 43,  33, 10,  19,  389, 276, 312)
#'                     
#' SKPWeights <- matrix(nrow = 1,
#'                   c(7,  0,  30, 22, 80, 94, 11, 81, 70, 64, 59, 18, 0,  36, 3,  8,  15,
#'                     42, 9,  0,  42, 47, 52, 32, 26, 48, 55, 6,  29, 84, 2,  4,  18, 56,
#'                     7,  29, 93, 44, 71, 3,  86, 66, 31, 65, 0,  79, 20, 65, 52, 13) )
#'                     
#'                     
#' SKPCapacities <- c(850)
#' 
#'  
#' SKPsolution <- solveMultiKnapsackProblem(SKPProfits, SKPWeights, SKPCapacities)
#' 
#' sum(SKPProfits[SKPsolution$packed_items]) # same as 'total_profit'
#' SKPWeights[SKPsolution$packed_items] # Items packed
#' sum(SKPWeights[SKPsolution$packed_items]) # Capacities used
#' 
#' 
#' #Example taken from ORtools docs
#' MKPprofits <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
#' MKPweights <- matrix(c(c(1, 2, 3, 4, 5, 6, 7, 8, 9),
#'                    c(1, 1, 1, 1, 1, 1, 1, 1, 1)),
#'                    nrow = 2, byrow = TRUE)
#' 
#' MKPcapacities <- c(34,4)
#' 
#' 
#' MKPsoolution <- solveMultiKnapsackProblem(MKPprofits, MKPweights, MKPcapacities)
#' MKPsoolution
#' 
#' sum(MKPprofits[MKPsoolution$packed_items]) # same as 'total_profit'
#' MKPweights[,MKPsoolution$packed_items] # Items packed
#' rowSums(MKPweights[,MKPsoolution$packed_items]) # Capacities used
#' 
#' @export
solveMultiKnapsackProblem <- function(profits, weights, capacities) {
    .Call('_RcppORtools_solveMultiKnapsackProblem', PACKAGE = 'RcppORtools', profits, weights, capacities)
}

