# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A simple TSP solver
#'
#'
#' Givent a matrix of pairwise distances, compute a travelling salesman problem solution that visits each
#' location once and only once before returning to the start.
#' 
#' @examples
#' distMatrix <- matrix(c(
#' 0, 2451, 713, 1018, 1631, 1374, 2408, 213, 2571, 875, 1420, 2145, 1972,
#' 2451, 0, 1745, 1524, 831, 1240, 959, 2596, 403, 1589, 1374, 357, 579,
#' 713, 1745, 0, 355, 920, 803, 1737, 851, 1858, 262, 940, 1453, 1260,
#' 1018, 1524, 355, 0, 700, 862, 1395, 1123, 1584, 466, 1056, 1280, 987,
#' 1631, 831, 920, 700, 0, 663, 1021, 1769, 949, 796, 879, 586, 371,
#' 1374, 1240, 803, 862, 663, 0, 1681, 1551, 1765, 547, 225, 887, 999,
#' 2408, 959, 1737, 1395, 1021, 1681, 0, 2493, 678, 1724, 1891, 1114, 701,
#' 213, 2596, 851, 1123, 1769, 1551, 2493, 0, 2699, 1038, 1605, 2300, 2099,
#' 2571, 403, 1858, 1584, 949, 1765, 678, 2699, 0, 1744, 1645, 653, 600,
#' 875, 1589, 262, 466, 796, 547, 1724, 1038, 1744, 0, 679, 1272, 1162,
#' 1420, 1374, 940, 1056, 879, 225, 1891, 1605, 1645, 679, 0, 1017, 1200,
#' 2145, 357, 1453, 1280, 586, 887, 1114, 2300, 653, 1272, 1017, 0, 504,
#' 1972, 579, 1260, 987, 371, 999, 701, 2099, 600, 1162, 1200, 504, 0), nrow = 13, byrow = TRUE)
#' 
#' singleVisitorTSP(distMatrix, 3)
#' 
#' @export
singleVisitorTSP <- function(distance_matrix, startIndex = 1L) {
    .Call('_RcppORtools_singleVisitorTSP', PACKAGE = 'RcppORtools', distance_matrix, startIndex)
}

#' A simple knapsack solver
#' 
#' Solve knapsack proble via google's brilliant OR tools lbirary.
#' 
#' @param profits A vector of integer item profits (must be equal in length to ncol(weights))
#' @param weights A matrix (which can have a single row if one is only interested in the standard knapsack problem) of item weights
#' @param capacities A vector of length nrow(weights) of knapsack capacities
#' 
#' @return solution A named list of:
#'            'packed_items' - the 1-based indicies of items selected for packing
#'            'total_profit' - the optimised sum of profits
#'            'is_optimal' - a status flag provided by the solver
#' @references \url{https://developers.google.com/optimization/reference/algorithms/knapsack_solver/}
#' @references \url{https://en.wikipedia.org/wiki/Knapsack_problem}
#' 
#' @examples
#' # Taken from the OR-tools documentation examples:
#' 
#' SKPProfits <- c(360, 83, 59,  130, 431, 67, 230, 52,  93,  125, 670, 892, 600,
#'                     38,  48, 147, 78,  256, 63, 17,  120, 164, 432, 35,  92,  110,
#'                     22,  42, 50,  323, 514, 28, 87,  73,  78,  15,  26,  78,  210,
#'                     36,  85, 189, 274, 43,  33, 10,  19,  389, 276, 312)
#'                     
#' SKPWeights <- matrix(nrow = 1,
#'                   c(7,  0,  30, 22, 80, 94, 11, 81, 70, 64, 59, 18, 0,  36, 3,  8,  15,
#'                     42, 9,  0,  42, 47, 52, 32, 26, 48, 55, 6,  29, 84, 2,  4,  18, 56,
#'                     7,  29, 93, 44, 71, 3,  86, 66, 31, 65, 0,  79, 20, 65, 52, 13) )
#'                     
#'                     
#' SKPCapacities <- c(850)
#' 
#'  
#' SKPsolution <- solveMultiKnapsackProblem(SKPProfits, SKPWeights, SKPCapacities)
#' 
#' sum(SKPProfits[SKPsolution$packed_items]) # same as 'total_profit'
#' SKPWeights[SKPsolution$packed_items] # Items packed
#' sum(SKPWeights[SKPsolution$packed_items]) # Capacities used
#' 
#' 
#' #Example taken from ORtools docs
#' MKPprofits <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
#' MKPweights <- matrix(c(c(1, 2, 3, 4, 5, 6, 7, 8, 9),
#'                    c(1, 1, 1, 1, 1, 1, 1, 1, 1)),
#'                    nrow = 2, byrow = TRUE)
#' 
#' MKPcapacities <- c(34,4)
#' 
#' 
#' MKPsoolution <- solveMultiKnapsackProblem(MKPprofits, MKPweights, MKPcapacities)
#' MKPsoolution
#' 
#' sum(MKPprofits[MKPsoolution$packed_items]) # same as 'total_profit'
#' MKPweights[,MKPsoolution$packed_items] # Items packed
#' rowSums(MKPweights[,MKPsoolution$packed_items]) # Capacities used
#' 
#' @export
solveMultiKnapsackProblem <- function(profits, weights, capacities) {
    .Call('_RcppORtools_solveMultiKnapsackProblem', PACKAGE = 'RcppORtools', profits, weights, capacities)
}

